### ISSUE TITLE
v1.5 Submission Checklist

### ISSUE THREAD

**Issue by Xenonym** [nus-cs2103-AY1718S1/forum#224]
Hey all, this is not _quite_ a feature reuse offer, but here's a checklist I made for the v1.5 submission requirements! If you copy-paste the Markdown source below into a new issue in your team repo, you can get your own copy of this checklist.

```
# On GitHub
## Test data
- [ ] Testing data added to `src\test\data\ManualTesting\[TEAM_ID][TEAM_NAME]SampleData.xml`
    - [ ] Testing data contains >= 20 items
- [ ] Testing script added to `src\test\data\ManualTesting\[TEAM_ID][TEAM_NAME]TestScript.adoc`
    - [ ] Starts with how to load sample data
    - [ ] Covers all functionality of the product
    - [ ] Grouped by functionality
    - [ ] Specify command to type and expected results (screenshots optional)
    - [ ] Limit to ~20 minutes of testing
## Source code
- [ ] All pull requests are closed / merged
- [ ] Build is passing
- [ ] All code is collated
## Documentation
- [ ] User Guide is up-to-date
    - [ ] Unused portions are removed
- [ ] Developer Guide is up-to-date
    - [ ] Unused portions are removed
- [ ] Project Portfolio Pages are up-to-date
- [ ] `README` is up-to-date
    - [ ] `Ui.png` in `README` matches the current product
- [ ] About Us is up-to-date
    - [ ] Contains a link to each person's Project Portfolio
    - [ ] Team member names match full names used in IVLE
## Project management
- [ ] All issues are assigned to a milestone
- [ ] All issues up to v1.5 milestone are closed
- [ ] v1.5 milestone is closed
- [ ] v1.5 release is created with JAR file attached
# On IVLE
**[Upload here!](https://ivle.nus.edu.sg/v1/File/Student/default.aspx?CourseID=08e0672a-67d5-433f-a66c-6a187939a79a&workbinid=a51fb28d-4628-42a1-8bcf-ce39cab5b9c4&FolderID=a47d5d4b-2b03-47e3-9825-8781992d4ed2)**
- [ ] JAR file uploaded as `[TEAM_ID][TEAM_NAME].jar`
- [ ] Documentation uploaded in [PDF format](https://nus-cs2103-ay1718s1.github.io/addressbook-level4/DeveloperGuide.html#converting-documentation-to-pdf-format)
    - [ ] Test script uploaded in PDF format as `[TEAM_ID][TEAM_NAME]TestScript.pdf`
    - [ ] User guide uploaded in PDF format as `[TEAM_ID][TEAM_NAME]UserGuide.pdf`
    - [ ] Developer guide uploaded in PDF format as `[TEAM_ID][TEAM_NAME]DeveloperGuide.pdf`
    - [ ] Project Portfolios uploaded in PDF format as `[TEAM_ID][YOUR_NAME]Portfolio.pdf`
```

Good luck to everyone for this final rush!! 😅

**Comment by damithc** [comment]
Nice. Just a comment with respect to `[ ] Unused portions are removed`, both UG and DG can contain 'proposed' features not yet implemented. Were you told to remove those by someone, e.g. CS2101 side?

**Comment by Xenonym** [comment]
@damithc apologies for the late reply! "Unused" actually means closer to outdated - in the case of our team's developer guide, we still had `Suggested Programming Tasks to Get Started`.
